### ISSUE TITLE
Cannot import viselect.min.mjs with CRA (create react app)

### ISSUE THREAD

**Issue by ParisRio** [Simonwep/selection#128]
#### What is the problem?
I have a JS react app created with CRA. I installed selection with:
`npm install @viselect/react`
then inserted on top of a component:
`import SelectionArea, {SelectionEvent} from '@viselect/react';`

#### What is the current behavior?

> Failed to compile
> ./node_modules/@viselect/react/lib/viselect.min.mjs
> Can't import the named export 'createRef' from non EcmaScript module (only default export is available)

#### Your environment:
```
Toolset (e.g. webpack, vite, vue-cli...): CRA, LocalHost, JS
Version (@viselect/<insert package>): "@viselect/react": "^3.0.0-beta.2",
Browser:  Firefox
OS:  Mac-Os
```
https://github.com/formatjs/formatjs/issues/1395 thread mentions
`CRA doesn't support mjs`

Could it be this? I am a React beginner and was wondering if someone have a simple solution. Thanks :)

**Comment by Simonwep** [comment]
Hey :) First of all thank you for trying out the beta! Yeah CRA is a bit tricky to handle due to it's many "legacy" dependencies, I can highly recomment trying out [vite](https://vitejs.dev/) or [preact](https://preactjs.com/) instead if you're interested.

Regarding CRA. I will try to find a solution for it as many are using it! I'll get back to it this weekend.

**Comment by Simonwep** [comment]
Okay, I think this is fixed in https://github.com/Simonwep/selection/commit/e9ccd001730424c1554eea984e5696eec95858d1, `v3.0.0.-beta4`

**Comment by ParisRio** [comment]
Problem solved after the update. Many thanks Simon.

Let's have fun now.
