### ISSUE TITLE
Question about goal of the Library

### ISSUE THREAD

**Issue by jogibear9988** [Simonwep/selection#179]
I've a question, I'm working on a designer wich is also able to select elements and move them around: https://node-projects.github.io/web-component-designer-demo/index.html.
Is this also thought iin this direction? Also to move elements? Or only for selecting them? What do you do with the selection?

**Comment by Simonwep** [comment]
Hi :) This library is just for selecting elements - since dragging is a whole new thing, this up to you to handle (either by another third-party library or by yourself). It aims to be minimalistic (at least as good as it gets with the current amount of features) without being bloaded... in your case you _could_ use viselect if you want to implement the _selection_ part. Notice that it's not just selecting elements but also selecting a range and inverse / exclude / include selection via ctrl / command what you can do with viselect.

The initial idea came from when I implemented a [google drive clone](https://github.com/ovanta/vue-cloudfront) where I needed such a feature (literally selecting folders / files and deleting them for example). So what you do with the selection is basically up to you, see it like something such as [popperjs](https://popper.js.org/) - it's just the core functionality which probably you don't want to implement yourself as there are like a million things to think and forget of when doing so.
