### ISSUE TITLE
Manually select and range select by shift key

### ISSUE THREAD

**Issue by Radius2** [Simonwep/selection#184]
I use `SelectionArea.select()`  for manually select in my project. And sometime I get unexpected result in range select by shift key because  `SelectionArea.select()` method doesn't overwrite `_latestElement` in `SelectionArea`.

**How can I drop/overwrite `_latestElement` manually ?**

**Comment by Simonwep** [comment]
I see, currently the last element that first element stored is used as "entry point" for when performing a range-select. Instead of making it possible to specify the latest element (which would be an ugly addition considering the current API), I'd instead of picking the first element the _closest_ when the last element is not known (for example due to using `.select()` - would this fix the problem in your case? With "closest" I mean the element with the smallest distance to the element where the range-selection is made.

PS: Please do not remove the issue template the next time, if the issue wouldn't be somewhat obvious to me I'd mark it as invalid and close it straight away as it's much easier for me to fix it if the template is used :)

**Comment by Radius2** [comment]
https://user-images.githubusercontent.com/25176930/202902869-73fd8997-d765-47b9-b3c6-1d15516cb047.mp4

[**Code from video** ](https://codesandbox.io/s/xenodochial-visvesvaraya-zjyjv7?file=/src/index.js:1129-1146)


**Path:**

1) _Click_ on 6th element;
2) _Click_ on the button for manually selection of 3rd element;
3) _Click with Shift_ on 9th element.

**Result:** range selection from 6th to 9th 
**Expected result:**  range selection from 3rd to 9th 

In my case I want to clear `_lastElement` when perform `.clearSelection()` method.

**Comment by Simonwep** [comment]
Gotchya, I'll clear `_lastElement` in both `select`, `deselect` and `clearSelection` as it'll only lead to confusion.
I'll also make a change that the move event is called in `clearSelection` just like in `deselect` - it can lead to an inconsistent state manually removing the active class and calling `clearSelection` ^^
