### ISSUE TITLE
Sequenced selections are buggy

### ISSUE THREAD

**Issue by adelin-b** [Simonwep/selection#196]
#### What is the problem?
Selections in secquences have buggy behavior

#### What is the current behavior?
Selection doesn't behave logically

#### Please provide the steps to reproduce and create a [CodeSandbox](https://codesandbox.io/).

To reproduce: https://simonwep.github.io/selection/

##### S-click + S-click + S-click + ... + S-click
![shiftright](https://user-images.githubusercontent.com/23508913/229861276-87414fac-e6b2-4749-82b2-e78f52fd4bf8.gif)
Expected: Should add to the selection without removing the first element.

##### S-click + S-click (This time going up)
![leftshiftclick](https://user-images.githubusercontent.com/23508913/229861509-6af1bcf9-1c30-4428-96e5-75309e217249.gif)
Expected: It shouldn't deselect all but two files. should select only one like in file manager. (starting and ending element are the same, so only one selected)

##### click + S-click + C-click + S-click
![ctrlshift](https://user-images.githubusercontent.com/23508913/229861731-5d949b59-bbfb-422b-92fb-f846f22291ba.gif)
Expected: S-click after C-click should select from the C-clicked element and not the first of the whole selection.

#### What is the expected behavior?
cf expected
#### Your environment:
```
Version (@viselect/lastest):
Browser: Chrome 
OS:  linux
```

**Comment by Simonwep** [comment]
Thank you for collecting all these bugs! I'll investigate and fix them this weekend :) Makes me consider rewriting the core of it, it's been almost 5 years haha

**Comment by Simonwep** [comment]
Just a small update, I saw your PR and will review it next weekend (I'm on vacation right now), I'll probably force-push to your branch since you re-formatted the whole codebase, or I'll fix it directly on master and add prettier or so to avoid such issues in the future! Either way, thank you for your time so far!

**Comment by adelin-b** [comment]
ah shit, yeah I use prettier by default on everyfile I touch, And I do not see how to revert the changes as they are all included.
I recommend using it to avoid having diff poluted with spaces.

**Comment by Simonwep** [comment]
The reason I didn't set up prettier for this project in particular so far, is that the code is, from the way it's written, pretty complex and manual formatting helped me maintaining it. Prettier will make it consistent, but at the cost of readability, especially in a non-project environment where you have "little" code, but high complexity :/

**Comment by Simonwep** [comment]
Okay, I decided to check out your commit and fix in on master! Thank you for your help, there were quite a few issues with  range selection - I decided to, for example, remove range-selection after selecting an "area" entirely because then the "latest element" is subjective to the user. I'll release a patch release shortly after this comment :) Happy holidays!
