### ISSUE TITLE
Unselecting the last element doesn't trigger `move` and `stop`

### ISSUE THREAD

**Issue by carlos-algms** [simonwep/selection#238]
#### What is the problem?

Clicking on an element to select it and then clicking again to unselect it doesn't trigger the events `move` and `stop` events. 

it can be fixed by removing the `if` 
https://github.com/simonwep/selection/blob/bee9f2faa521a220c1393103fff7b40879f873ec/packages/vanilla/src/index.ts#L805-L807

#### Please provide the steps to reproduce and create a [CodeSandbox](https://codesandbox.io/).

https://codesandbox.io/p/sandbox/ynjtdj

Also, check the `console.log`

1. Select elements by clicking or dragging a selection
2. unselect and leave only 1 element
3. click on that last element

Check the events were NOT triggered.

#### What is the expected behavior?

It should trigger the `move` and `stop` events and `stop` should contain the right `stored` data so we can trust it.

**Comment by carlos-algms** [comment]
Hey @simonwep I've created this small PR #239 removing the block I found was blocking the events from being triggered. 

I managed to test it locally by building and installing the local version. 

Please let me know what you think.

**Comment by simonwep** [comment]
Hey @carlos-algms, thank's for the elaborate issue and reproduction! But I'm a little bit confused, because if it wouldn't emit the `move` and `stop` events even the simplest selections wouldn't work. I tried it locally and all events seemed to be triggered correctly:

![selection-events](https://github.com/user-attachments/assets/a753ba53-10bc-4483-a068-fee4cd58f940)

Also in your codesandbox you do a lot with timeouts _inside_ of the callbacks, accessing the values after the might have been changed again by viselect. Could you elaborate what you believe is the issue here? Is it that you would expect `stored` to be empty if it's also listed in `changed.removed` in the `stop` event?

**Comment by carlos-algms** [comment]
Hey, thanks for investigating it 😊. 

The `stop` event you see comes from the `clearSelection()` call, not from the `unselect()`.
```json
{
  "added": [],
  "removed": [
    "A"
  ],
  "stored": [
    "A"  // note even tho it was removed, it's still included here.
  ]
}
``` 
and it should be
```json
{
  "added": [],
  "removed": [
    "A"
  ],
  "stored": [] // I'd expect it to be empty, as it is the last event I'll receive.
}
```

I put a timeout there to check the internal state is updated after some time, and `stored` will be empty, but not on the last `stop` event.

**Comment by simonwep** [comment]
Aaah, I see! I get why this might be confusing and I'd really like to change it. Even though this is not expected, it's a somewhat "minor" breaking change. I'll have to have a closer look at it to not break anything else (back then I didn't set up E2E tests so any change to such a core thing is critical). I'm currently on vacation but will have a look at it! Thank you again for your clarification :)
