### ISSUE TITLE
Exclude blocks from selection.

### ISSUE THREAD

**Issue by crashbdx** [Simonwep/selection#25]
Hello, was wondering if there is a way to exclude block from being selected, like for exemple i have a 100x100 area of square, someone select 6x6 (36 blocks) anywhere in the area and save it, then someone else cannot select this 6x6 anymore. Is there such option already to exclude blocks ?

**Comment by crashbdx** [comment]
Awesome, will be very nice feature :)

**Comment by Simonwep** [comment]
Just thought this can be realized using [selectionFilter](https://github.com/Simonwep/selection/blob/master/README.md#options) and a single helper variable. See [this JSFiddle](https://jsfiddle.net/r9zbxo7y/2/) - pay attention to the lines at the very bottom (from line 76) and the first line :)

**Comment by Simonwep** [comment]
1. Take a look at [Arrow Functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions), with these you can get rit of these `_this`.
2. `Array.from` transforms iterables to normal arrays, so you can do
```js
let excluded = Array.from(document.querySelectorAll('.excluded'));
```
3. Instead of using `DOMContentLoaded` which is IMO bad practice and reduces the readability of your code, place your script at the very bottom of the `body` element e.g:
```html
<body>
<!-- Awesome content -->
<script src="your/path/to/mybundle.min.js"></script> 
</body>
```

But apart from that, everything looks fine. Of course you could replace all `forEach`, `map` and other Array functions with `for i` loops, but that would only be required if you got some serious performance issues etc.

**Comment by crashbdx** [comment]
Perfect, will modify it thanks a lot :)

**Comment by Simonwep** [comment]
You're welcome 😃
