### ISSUE TITLE
When trying to drag an picture object which is draggable, the selection is getting started! How can I stop this?

### ISSUE THREAD

**Issue by Mohitkiran** [Simonwep/selection#49]
Thanks for creating this wonderful library, I am new to the field of development, please excuse me in case of irrelevant word usage.

I am trying to select picture objects that are created using Konva.js and then I want to know which objects are selected in the code so that I can group individual objects into one but here I am facing two problems. The first one is that the picture objects are draggable so when I am trying to drag the objects the selection is also getting enabled, in my case the selection should only be enabled when clicked on non draggable area and the second one is that when I am selecting the objects and using `var selectedItems = selection.getSelection();` to know the objects that are selected, it always returns the array of html element but I need an array of objects references that are selected (Like the variables of objects, like var box, box1, box2 in my code). So, is it possible to know which objects are selected in code?

Below is the fiddle.
[JSFiddle](https://jsfiddle.net/qu4h1yw0/7/).

#### Environment:
```
Selection-version: Using CDN
Browser-version:  Chrome version 75.0.3770.100 (Official Build) (64-bit)
Operating-system:  MacOS Mojave 10.14.3
```

**Comment by Simonwep** [comment]
You're welcome :)
First, I'd never use var. It's really deprecated and can cause really, really strange bugs. Stick to `const` or if you _really need to_ re-assign it use `let`. If you care about browser-support use [babel](https://babeljs.io/), but you're using object-deconstruction so I guess you already use it anyway.

The rectangles are drawn to a canvas which makes the situation kinda difficult since if they would be elements you could use the `beforestart` event to check if `event.path` contains one of these images / rectangles. In your case you'd need to check whenever the mouse-postition is in a rectangle (using `clientX` and `clientY` properties). You would **additionally** need to take the offset of the canvas into account if it's not positioned at `0|0`. So the procedure would be
1. Add `beforestart` event hook
2. Get `x/y` position of `oe` (original event) [read more...](https://github.com/Simonwep/selection#events)
3. Check if the cursor is in any of your rectangles
4. If yes return `false` in `beforestart` which would cancel the selection :)

**Comment by Mohitkiran** [comment]
Thank you Simon.
