### ISSUE TITLE
Selection with jquery.panzoom doesn't work correctly.

### ISSUE THREAD

**Issue by websitewill** [Simonwep/selection#63]
Maybe a bug, maybe a feature. Not sure.

Current behavior:
In conjunction with jquery.panzoom, the coordinates where selection starts are wrong after panning/zooming.
I've setup this jsfiddle as an example.
https://jsfiddle.net/websitewill/ah4k0gc2/12/
The links toggle the pan/select mode. If you go into pan mode and drag the div, then go to select mode and drag a selection, you'll see the selection window ends up being offset from where the mouse cursor is. 
**Recommend not panning by much otherwise you won't see the selection window at all.**

Expected:
Selection should start where mouse cursor is. Or, need a way to reinitialize the selection coordinates based on where pan/zoom is.

Selection-version: Latest
Browser-version:  Chrome latest
Operating-system:  Windows 10

**Comment by Simonwep** [comment]
Maybe related to #58, could you reduce your code to a minimum? I don't think all 195 Lines are related to this exact problem. Of what I can see `#pan` get's transformed but you're also using it as container for the selection-area. This won't work since the selection-area should always be fixed.

Using the body, or any other non-transformed element as parent works: https://jsfiddle.net/Lg20x3hm/

**Comment by websitewill** [comment]
Ahhh nice. You're right - that fixes it right up. Thanks and sorry for the bother.

**Comment by Simonwep** [comment]
You're welcome :) Glad I could help!
