### ISSUE TITLE
noStartAreas

### ISSUE THREAD

**Issue by Dozalex** [Simonwep/selection#73]
#### Do you want to request a **feature** or report a **bug**?
feature
#### What is the current behavior?
I want to start select from a container, but not from selectable elements.
For example, we have a container and a many elements with margin. 
And we need to use d'n'd for these elements. 
So selection must starts from gaps between these elements.
#### What is the expected behavior?
We need some option like
`
noStartAreas: ['someSelector']
`

In my project (React) i do it like that:
```javascript
const rowClassName = 'someClassName';

...

.on('beforestart', evt => {
    if (
      evt.oe.path.some(item => {
          if (item.className) {
              const classes = item.className.split(' ');

              if (classes.includes(rowClassName)) {
                  return true;
              }
          }

          return false;
      })
    ) {
           return false;
      }
})
```

May be there is a better solution but this works.
I hope this will be useful to someone :)

**Comment by Simonwep** [comment]
I would consider this as the best solution, `beforestart` was introduced for exactly this purpose. Anyway you can simplify your code by using [`classList`](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList) and removing redundant conditional-statements:

```js
on('beforestart', evt => {
    return !evt.oe.path.some(item => item.classList.contains(rowClassName));
});
```


First we check if there's any element with the class in `rowClassName`, then we negate the value since we _don't_ want the selection to start if we found such an element :)

If you use a conditional-statement to return `true` or `false` you can simply return the condition itself and negate it if necessary.

**Comment by Dozalex** [comment]
You are right, it will be more shortly :)
Minor fix:
```javascript
.on('beforestart',evt =>
    !evt.oe.path.some(
        item => item.classList && item.classList.contains(rowClassName),
    ),
)
```

**Comment by Simonwep** [comment]
I've created a [examples.md](https://github.com/Simonwep/selection/blob/master/EXAMPLES.md) file were future requests like this can be demonstrated :)
