### ISSUE TITLE
Scroll page in case the the container is out-of-bounds

### ISSUE THREAD

**Issue by naitik95** [Simonwep/selection#82]
Very helpful lib! Thanks a bunch!

I'm running into an issue with the scrollable container implementation. My grid container only has a horizontal scrollbar but not a vertical scrollbar. I'm using [handy-scroll](https://amphiluke.github.io/handy-scroll/) so that I can leverage page scrollbar for vertical scrolling and thus not have 2 vertical scrollbars (1 on page and other on the grid container).

I'm defining my grid selector in the "boundaries", but I'm not able to select cells while vertically scrolling. Horizontal scroll selection works perfectly. I tried adding 'html' and 'body' in "boundaries" but it didn't work. Could you please provide any suggestion/workaround code if possible.

**Comment by Simonwep** [comment]
It _supports_ both vertical and horizontal - or either one of them. handy-scroll doesn't seem to be maintained anymore. Could you please provide a [JSFiddle](https://jsfiddle.net/Simonwep/wez9o7cu) with a reproduction?

**Comment by naitik95** [comment]
https://jsfiddle.net/kqzuw7ba/  In your example, I removed height from the .container element, which removed the vertical scrollbar from the container and added the scroll bar at page level. In this case, drag selection downwards does not scroll down.

**Comment by Simonwep** [comment]
Okay first, this isn't really a "bug" because _what_ selectionjs _can do_, is scroll the container _itself_ - not the whole page as in your case, and this affects both the vertical and horizontal scrolling ^^

This seems to be a feature from Firefox because it works there... I'm not sure if I want do "polyfill" this for other browsers - and if I'd do that I'd have to do it for all sorts of nested, scrollable containers (the page itself counts as a container). For now I'd say it's better to limit the size of the scrollable area and make _it_ scrollable instead of letting the browser handle it.

Fixing this would mean to...
* Resolve **all** scrollable parents from the area?!
* Scroll each container accordingly (however that might be possible...).

You _can_, however, do it like this: https://jsfiddle.net/Simonwep/y8c57Ld9/ - although you'd have to handle I believe it fits your situation perfectly :)

**Comment by naitik95** [comment]
Your solution looks like it will work for my case, thank you.
